
trigger:
  branches:
    include:
    - develop
    - testing
    - main

pool:
  vmImage: 'ubuntu-18.04'
stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '5.0.x'
          displayName: 'Set SDK to 5.0.x'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '$(Build.SourcesDirectory)/src/AOM.FIFAManagerPlayer.Sync.API/AOM.FIFAManagerPlayer.Sync.API.csproj'
          displayName: 'Build backend service'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '$(Build.SourcesDirectory)/src/AOM.FIFAManagerPlayer.Sync.API/AOM.FIFAManagerPlayer.Sync.API.csproj'
            arguments: '-o $(Build.ArtifactStagingDirectory)'
          displayName: 'dotnet publish'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

        - task: PublishBuildArtifacts@1
          inputs:
            PathToPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))




